language: go

go:
  - 1.7
  - 1.8
  - 1.9

before_install:
  - go get -t -v ./...

script:
  - go test -coverprofile=coverage.txt -covermode=atomic

after_success:
  - bash <(curl -s https://codecov.io/bash)